apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: t95ftbs0g-go
  janus-idp.io/tekton: t95ftbs0g-go
  backstage.io/kubernetes-id: t95ftbs0g-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: t95ftbs0g-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
